Repository omsimos/umamin, pull requests merged in 2022-07, with the labels that each got.

#2 feat/add-user
  package.json
  prisma/schema.prisma
  src/api.ts
  src/components/Success.tsx
  src/generated/graphql.ts
  src/graphql/createUser.graphql
  src/graphql/getUser.graphql
  src/pages/_app.tsx
  src/pages/api/graphql.ts
  src/pages/create.tsx
  src/pages/inbox/[username].tsx
  src/schema/user/user.resolvers.ts
  src/schema/user/user.types.ts
  src/types/models.d.ts
  yarn.lock
Labels: feature

#4 copy link to clipboard feature
  src/pages/inbox/[username].tsx
Labels: feature

#7 fix ui issues
  src/pages/index.tsx
  src/pages/login.tsx
  src/styles/globals.css
Labels: fix

#8 login feature
  package.json
  src/api.ts
  src/components/Layout.tsx
  src/components/Navbar.tsx
  src/generated/graphql.ts
  src/graphql/loginUser.graphql
  src/hooks/index.ts
  src/hooks/useStore.ts
  src/pages/create.tsx
  src/pages/inbox/[username].tsx
  src/pages/index.tsx
  src/pages/login.tsx
  src/schema/user/user.resolvers.ts
  src/styles/globals.css
  yarn.lock
Labels: feature, chore

#12 fix(readme): change URL to umamin
  README.md
Labels: documentation, fix

#13 send message page ui
  src/pages/to/[username].tsx
  src/styles/chat.css
  src/styles/globals.css
  tailwind.config.js
Labels: feature

#14 send message feature
  prisma/schema.prisma
  src/api.ts
  src/components/Navbar.tsx
  src/generated/graphql.ts
  src/graphql/deleteMessage.graphql
  src/graphql/getMessageById.graphql
  src/graphql/getMessages.graphql
  src/graphql/sendMessage.graphql
  src/pages/api/graphql.ts
  src/pages/inbox/[username].tsx
  src/pages/index.tsx
  src/pages/to/[username].tsx
  src/schema/message/index.ts
  src/schema/message/message.resolvers.ts
  src/schema/message/message.types.ts
  src/schema/user/user.resolvers.ts
Labels: feature

#15 implement loader
  src/pages/create.tsx
  src/pages/inbox/[username].tsx
  src/pages/to/[username].tsx
  src/styles/globals.css
  src/styles/utils.css
Labels: feature

#20 chores
  package.json
  src/pages/_app.tsx
  src/pages/api/auth/[...nextauth].ts
  src/pages/api/graphql.ts
  src/pages/create.tsx
  src/pages/login.tsx
  src/schema/user/user.resolvers.ts
  src/styles/utils.css
  yarn.lock
Labels: chore

#21 dev to main
  .env.example
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  README.md
  docker-compose.yml
  package.json
  prisma/schema.prisma
  prisma/seed.js
  src/api.ts
  src/components/Navbar.tsx
  src/components/Success.tsx
  src/generated/graphql.ts
  src/graphql/deleteMessage.graphql
  src/graphql/getMessageById.graphql
  src/graphql/getMessages.graphql
  src/graphql/sendMessage.graphql
  src/hooks/index.ts
  src/hooks/useStore.ts
  src/pages/_app.tsx
  src/pages/api/auth/[...nextauth].ts
  src/pages/api/authorize.ts
  src/pages/api/graphql.ts
  src/pages/create.tsx
  src/pages/inbox.tsx
  src/pages/inbox/[username].tsx
  src/pages/index.tsx
  src/pages/login.tsx
  src/pages/to/[username].tsx
  src/schema/message/index.ts
  src/schema/message/message.resolvers.ts
  src/schema/message/message.types.ts
  src/schema/user/user.resolvers.ts
  src/styles/globals.css
  src/styles/utils.css
  src/types/next-auth.d.ts
  src/utils.ts
  tailwind.config.js
  yarn.lock
Labels: documentation, feature, chore

#22 add footer
  src/components/Footer.tsx
  src/components/Layout.tsx
  src/components/Navbar.tsx
  src/components/Success.tsx
  src/components/index.ts
  src/constants.ts
  src/pages/inbox.tsx
  src/pages/index.tsx
  src/styles/globals.css
Labels: feature, chore

#24 feat: message sent ui
  src/pages/to/[username].tsx
Labels: feature

#25 menu on mobile view
  package.json
  src/components/Footer.tsx
  src/components/Menu.tsx
  src/components/Navbar.tsx
  src/components/index.ts
  src/constants.ts
  src/pages/create.tsx
  src/styles/globals.css
  yarn.lock
Labels: feature, chore

#27 add SEO & PWA
  .gitignore
  next-seo-config.js
  next.config.js
  package.json
  public/favicon.ico
  public/icons/apple-touch-icon.png
  public/icons/icon-128x128.png
  public/icons/icon-144x144.png
  public/icons/icon-152x152.png
  public/icons/icon-192x192.png
  public/icons/icon-384x384.png
  public/icons/icon-48x48.png
  public/icons/icon-512x512.png
  public/icons/icon-72x72.png
  public/icons/icon-96x96.png
  public/manifest.json
  src/pages/_app.tsx
  src/pages/to/[username].tsx
  yarn.lock
Labels: feature

#26 add register page
  package.json
  src/api.ts
  src/components/Footer.tsx
  src/components/Menu.tsx
  src/components/Navbar.tsx
  src/components/UserForm.tsx
  src/components/index.ts
  src/generated/graphql.ts
  src/graphql/createUser.graphql
  src/graphql/getUser.graphql
  src/graphql/loginUser.graphql
  src/pages/create.tsx
  src/pages/index.tsx
  src/pages/login.tsx
  src/pages/register.tsx
  src/schema/user/user.resolvers.ts
  yarn.lock
Labels: chore

#28 add receiver message
  .eslintrc.json
  prisma/schema.prisma
  src/generated/graphql.ts
  src/graphql/getMessageById.graphql
  src/graphql/getMessages.graphql
  src/graphql/getUser.graphql
  src/graphql/sendMessage.graphql
  src/pages/inbox.tsx
  src/pages/to/[username].tsx
  src/schema/message/message.resolvers.ts
  src/schema/message/message.types.ts
  src/schema/user/user.types.ts
  src/styles/globals.css
  tailwind.config.js
Labels: feature

#29 update inbox ui
  src/pages/inbox.tsx
  src/pages/to/[username].tsx
Labels: feature

#36 save image & share to instagram
  package.json
  public/icons/maskable-192x192.png
  public/icons/maskable-512x512.png
  src/components/Info.tsx
  src/components/MessageModal.tsx
  src/components/Navbar.tsx
  src/components/index.ts
  src/pages/inbox.tsx
  src/pages/to/[username].tsx
  src/styles/globals.css
  src/styles/utils.css
  yarn.lock
Labels: feature, fix

#37 add analytics using firebase
  package.json
  src/components/MessageModal.tsx
  src/components/UserForm.tsx
  src/firebase.ts
  src/hooks/index.ts
  src/hooks/useLogEvent.ts
  src/pages/inbox.tsx
  src/pages/to/[username].tsx
  yarn.lock
Labels: feature

#38 seen indicator
  prisma/schema.prisma
  src/api.ts
  src/components/MessageModal.tsx
  src/generated/graphql.ts
  src/graphql/editMessage.graphql
  src/graphql/getMessages.graphql
  src/pages/inbox.tsx
  src/schema/message/message.resolvers.ts
  src/schema/message/message.types.ts
  src/schema/user/user.types.ts
Labels: feature

#40 feat: custom message
  .husky/pre-commit
  src/api.ts
  src/components/Dialog/Container.tsx
  src/components/Dialog/Message.tsx
  src/components/Dialog/Settings.tsx
  src/components/Dialog/index.ts
  src/components/Footer.tsx
  src/components/MessageModal.tsx
  src/components/index.ts
  src/generated/graphql.ts
  src/graphql/editUser.graphql
  src/hooks/index.ts
  src/hooks/useUser.ts
  src/pages/inbox.tsx
  src/pages/to/[username].tsx
  src/schema/user/user.resolvers.ts
  src/styles/globals.css
Labels: feature

#41 update message ui
  src/api.ts
  src/components/Dialog/Container.tsx
  src/components/Dialog/Message.tsx
  src/components/Dialog/Settings.tsx
  src/components/Navbar.tsx
  src/pages/inbox.tsx
  src/styles/globals.css
Labels: chore

#42 add privacy policy
  package.json
  src/components/Markdown.tsx
  src/components/index.ts
  src/constants.ts
  src/pages/privacy-policy.tsx
  tailwind.config.js
  yarn.lock
Labels: chore

#44 fix: message dialog padding css conflict
  src/components/Dialog/Message.tsx
  src/pages/to/[username].tsx
  src/styles/utils.css
Labels: fix

#47 minor changes
  src/components/Dialog/Settings.tsx
  src/pages/to/[username].tsx
Labels: chore

#53 fix(ci): add missing steps
  .github/workflows/db.yml
Labels: fix

#55 feat(ci): separate db branches
  .github/workflows/db-dev.yml
  .github/workflows/db-main.yml
Labels: workflows

#56 feat(ci): separate db branches
  .github/workflows/db-dev.yml
  .github/workflows/db-main.yml
Labels: workflows

#57 feat: add donate page
  src/constants.ts
  src/pages/donate.tsx
Labels: feature

#58 add donation page v0.1.2
  src/constants.ts
  src/pages/donate.tsx
Labels: feature, release

#62 chore: minor changes on maintenance page
  src/components/Maintenance.tsx
  src/pages/_app.tsx
Labels: chore

#63 setup AdSense
  next-seo-config.js
  src/pages/_app.tsx
  src/pages/index.tsx
Labels: feature

#64 dev to main
  .github/FUNDING.yml
  next-seo-config.js
  prisma/migrations/20220729110414_remove_is_downloaded_field/migration.sql
  prisma/schema.prisma
  src/components/Success.tsx
  src/components/index.ts
  src/generated/graphql.ts
  src/graphql/sendMessage.graphql
  src/pages/_app.tsx
  src/pages/index.tsx
  src/pages/to/[username].tsx
  src/schema/message/message.resolvers.ts
  src/schema/message/message.types.ts
  src/schema/user/user.resolvers.ts
  src/schema/user/user.types.ts
Labels: feature, fix

#65 fix: add beforeInteractive
  src/pages/_app.tsx
Labels: fix

#66 pagination
  src/generated/graphql.ts
  src/graphql/getMessages.graphql
  src/pages/inbox.tsx
  src/schema/message/message.resolvers.ts
Labels: feature

#67 implement pagination
  src/generated/graphql.ts
  src/graphql/getMessages.graphql
  src/pages/inbox.tsx
  src/schema/message/message.resolvers.ts
Labels: feature

#68 chores
  README.md
  public/fonts/Inter-Medium.ttf
  public/fonts/Inter-Medium.woff2
  public/fonts/Syne-ExtraBold.ttf
  public/fonts/Syne-ExtraBold.woff2
  src/components/Maintenance.tsx
  src/constants.ts
  src/pages/_app.tsx
  src/pages/to/[username].tsx
  src/styles/globals.css
Labels: chore, fix

#69 minor changes
  README.md
  public/fonts/Inter-Medium.ttf
  public/fonts/Inter-Medium.woff2
  public/fonts/Syne-ExtraBold.ttf
  public/fonts/Syne-ExtraBold.woff2
  src/components/Maintenance.tsx
  src/constants.ts
  src/pages/_app.tsx
  src/pages/to/[username].tsx
  src/styles/globals.css
Labels: chore

#71 fix: update inbox pagination
  README.md
  src/pages/inbox.tsx
Labels: fix

#74 chores
  README.md
  next.config.js
  package.json
  src/constants.ts
  src/pages/api/graphql.ts
  yarn.lock
Labels: chore

#75 release: v0.1.5
  README.md
  next.config.js
  package.json
  prisma/migrations/20220729110414_remove_is_downloaded_field/migration.sql
  public/ads.txt
  src/components/UserForm.tsx
  src/constants.ts
  src/hooks/useUser.ts
  src/pages/api/graphql.ts
  src/pages/inbox.tsx
  yarn.lock
Labels: chore
