Repository omsimos/umamin, pull requests merged in 2022-11, with the labels that each got.

#117 fix pwa in next config
  apps/web/next.config.js
  apps/web/package.json
  apps/web/public/manifest.json
  apps/web/src/components/Dialog/Reply.tsx
  apps/web/src/components/Footer.tsx
  apps/web/src/components/InboxTabs/Recent.tsx
  apps/web/src/components/InboxTabs/Sent.tsx
  apps/web/src/components/Maintenance.tsx
  apps/web/src/components/Navbar.tsx
  apps/web/src/components/UserForm.tsx
  apps/web/src/pages/inbox.tsx
  apps/web/src/pages/index.tsx
  apps/web/src/pages/to/[username].tsx
  yarn.lock
Labels: chore, fix

#118 release: v0.3.2
  apps/web/.eslintrc.json
  apps/web/.gitignore
  apps/web/next.config.js
  apps/web/package.json
  apps/web/public/manifest.json
  apps/web/src/components/Create.tsx
  apps/web/src/components/Dialog/Message.tsx
  apps/web/src/components/Dialog/Reply.tsx
  apps/web/src/components/Dialog/Settings.tsx
  apps/web/src/components/Footer.tsx
  apps/web/src/components/ImageFill.tsx
  apps/web/src/components/InboxTabs/Recent.tsx
  apps/web/src/components/InboxTabs/Seen.tsx
  apps/web/src/components/InboxTabs/SeenCard.tsx
  apps/web/src/components/InboxTabs/Sent.tsx
  apps/web/src/components/Maintenance.tsx
  apps/web/src/components/Navbar.tsx
  apps/web/src/components/UserForm.tsx
  apps/web/src/pages/_app.tsx
  apps/web/src/pages/_document.tsx
  apps/web/src/pages/api/graphql.ts
  apps/web/src/pages/help.tsx
  apps/web/src/pages/inbox.tsx
  apps/web/src/pages/index.tsx
  apps/web/src/pages/login.tsx
  apps/web/src/pages/privacy-policy.tsx
  apps/web/src/pages/register.tsx
  apps/web/src/pages/to/[username].tsx
  apps/web/src/schema/message/message.resolvers.ts
  apps/web/src/schema/message/message.types.ts
  apps/web/src/schema/user/user.resolvers.ts
  packages/generated/graphql/message.graphql
  packages/generated/graphql/user.graphql
  packages/generated/index.ts
  yarn.lock
Labels: chore, fix, release

#119 chore: update button when user is authed
  apps/web/src/pages/to/[username].tsx
Labels: feature

#120 add install pwa button
  apps/web/package.json
  apps/web/src/components/ImageFill.tsx
  apps/web/src/components/InboxTabs/Recent.tsx
  apps/web/src/components/InboxTabs/Sent.tsx
  apps/web/src/components/Maintenance.tsx
  apps/web/src/components/Navbar.tsx
  apps/web/src/components/UserForm.tsx
  apps/web/src/pages/index.tsx
  apps/web/src/pages/to/[username].tsx
  yarn.lock
Labels: feature, chore

#121 release: v0.3.3
  apps/web/package.json
  apps/web/src/components/ImageFill.tsx
  apps/web/src/components/InboxTabs/Recent.tsx
  apps/web/src/components/InboxTabs/Sent.tsx
  apps/web/src/components/Maintenance.tsx
  apps/web/src/components/Navbar.tsx
  apps/web/src/components/UserForm.tsx
  apps/web/src/pages/index.tsx
  apps/web/src/pages/to/[username].tsx
  yarn.lock
Labels: feature, chore, release
